# Generated by Django 3.2.9 on 2021-11-15 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=200)),
                ("creation_date", models.CharField(max_length=200)),
                ("amount_of_upvotes", models.CharField(max_length=200)),
                ("author_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=70)),
                ("content", models.CharField(max_length=300)),
                ("creation_date", models.CharField(max_length=8)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news_board.news",
                    ),
                ),
            ],
        ),
    ]
