# Generated by Django 3.2.9 on 2021-11-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_board", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="news",
            new_name="news_f",
        ),
        migrations.AlterField(
            model_name="comments",
            name="author_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="comments",
            name="content",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="comments",
            name="creation_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="news",
            name="amount_of_upvotes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="news",
            name="author_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="news",
            name="creation_date",
            field=models.DateTimeField(),
        ),
    ]
