# Generated by Django 3.2.9 on 2021-11-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_board', '0002_auto_20211116_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
            ],
        ),
    ]
